CustoFuncionarioApp/Models/ErrorViewModel.cs
namespace AtividadeFuncionario.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustoFuncionarioApp/Models/Funcionario.cs
using System.ComponentModel.DataAnnotations;

namespace AtividadeFuncionario.Models
{
    public class Funcionario
    {
        [StringLength(30, ErrorMessage = "O nome pode ter no máximo 30 caracteres.")]
        public string Nome { get; set; }
        public decimal SalarioClt { get; set; }
        public decimal Desconto { get; set; }
        public decimal Beneficio { get; set; }
    }
}

CustoFuncionarioApp/Controllers/FuncionarioController.cs
using AtividadeFuncionario.Models;
using Microsoft.AspNetCore.Mvc;

namespace AtividadeFuncionario.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Calcular(Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                var custoFuncionario = CalcularCustoFuncionario(funcionario);
                ViewData["CustoFuncionario"] = custoFuncionario;
            }

            return View("Index", funcionario);
        }

        public static decimal CalcularCustoFuncionario(Funcionario funcionario)
        {
            return funcionario.SalarioClt + funcionario.Beneficio - funcionario.Desconto;
        }
    }
}

CustoFuncionarioApp/Controllers/HomeController.cs
using AtividadeFuncionario.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AtividadeFuncionario.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustoFuncionarioApp/Views/Funcionario/Index.cshtml
@model AtividadeFuncionario.Models.Funcionario

<h2>Cálculo do Custo do Funcionário</h2>
<hr />
<div class="d-flex justify-content-around">
    <div class="col-5">
        <form asp-action="Calcular">
            <div class="form-group">
                <label for="Nome">Nome</label>
                <input type="text" class="form-control" id="Nome" name="Nome" value="@Model?.Nome" required placeholder="Nome do Funcionario" maxlength="25" />
            </div>

            <div class="form-group">
                <label for="SalarioClt">Salário Base</label>
                <input type="number" class="form-control" id="SalarioClt" name="SalarioClt" step="1" value="@Model?.SalarioClt" required placeholder="Valor do Sálario Base" />
            </div>

            <div class="form-group">
                <label for="Desconto">Desconto</label>
                <input type="number" class="form-control" id="Desconto" name="Desconto" step="1" value="@Model?.Desconto" required placeholder="Total de Descontos do funcionario" />
            </div>

            <div class="form-group">
                <label for="Beneficio">Benefício</label>
                <input type="number" class="form-control" id="Beneficio" name="Beneficio" step="1" value="@Model?.Beneficio" required placeholder="Total de Benefícios do funcionario" />
            </div>

            <button type="submit" class="btn btn-primary mt-3 col-12">Calcular</button>
        </form>
    </div>

    <div class="col-5">
        @if (ViewData["CustoFuncionario"] != null)
        {
            <div class="d-flex justify-content-between">
                <label for="CustoFuncionario" class="mr-2">
                    Custo Final do Funcionário:
                </label>
                <span> @Model.Nome</span>
            </div>

            <div>
                <input type="text" class="form-control" id="CustoFuncionario" readonly value="@ViewData["CustoFuncionario"].ToString()" />
            </div>

        }
    </div>
</div>

CustoFuncionarioApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CustoFuncionarioApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtividadeFuncionario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AtividadeFuncionario.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AtividadeFuncionario</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AtividadeFuncionario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>